# Generated by Django 4.2.1 on 2023-07-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(db_index=True, default=0),
        ),
    ]
